---
# Post tasks

- name: POST | Perform DNF package cleanup
  ansible.builtin.dnf:
    autoremove: true

- name: POST | flush handlers
  ansible.builtin.meta: flush_handlers

- name: POST | reboot system if changes require it and not skipped
  when: reboot_required
  tags: always
  vars:
    warn_control_id: Reboot_required
  block:
    - name: POST | Reboot system if changes require it and not skipped
      when: not skip_reboot
      ansible.builtin.reboot:

    - name: POST | Warning a reboot required but skip option set
      when: skip_reboot
      ansible.builtin.debug:
        msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
      changed_when: reboot_warning_changed_when

    - name: "POST | Warning a reboot required but skip option set | warning count"
      when: skip_reboot
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: If Warning count is 0 set fact
  when: warn_count == '0'
  ansible.builtin.set_fact:
    control_number: "Congratulation None Found"
